<?php

/**
 * @file
 * Functions to support theming in the Bootstrap for Drupal subtheme.
 */

use Drupal\block\Entity\Block;
//  bfd
use Drupal\Core\Form\FormStateInterface;
// classy
//use Drupal\Core\Form\FormStateInterface;
use Drupal\views\Form\ViewsForm;
// stable
use Drupal\Component\Utility\Html;


/**
 * Implements hook_theme_suggestions_HOOK().
 */
function bfd_systopia_theme_suggestions_form_element_alter(array &$suggestions, array $variables) {
  $suggestions[] = 'form_element__type__' . $variables['element']['#type'];

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function bfd_systopia_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  // Suggest region-dependent block template name.
  if (!empty($variables['elements']['#id'])) {
    /* @var Block $block */
    $block = Block::load($variables['elements']['#id']);
    $suggestions[] = 'block__' . $block->getRegion() . '__' . $variables['elements']['#plugin_id'];
  }
  /* Use this 'else if' only if you are using page_manager module and want to know which region is the block */
  else if (isset($variables['elements']['#configuration']['region'])) {
    $region = explode(':', $variables['elements']['#plugin_id']);
    $suggestions[] = 'block__page_' . $variables['elements']['#configuration']['region'] . '__' . end($region);
  }
  return $suggestions;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bfd_systopia_preprocess_block(&$variables) {
  if ($variables['base_plugin_id'] == 'system_branding_block') {
    if (!$variables['content']['site_logo']['#access']) {
      $variables['site_logo'] = '';
    }
    if (!$variables['content']['site_name']['#access']) {
      $variables['site_name'] = '';
    }
    if (!$variables['content']['site_slogan']['#access']) {
      $variables['site_slogan'] = '';
    }
  }
}

// bfd theme

/**
 * Site name, logo and slogan global variable.
 */
function  bfd_systopia_preprocess(&$variables) {
  $site_config = \Drupal::config('system.site');
  $variables['site_name'] = $site_config->get('name');
  $variables['site_slogan'] = $site_config->get('slogan');
  // $variables['logopath'] = file_url_transform_relative(file_create_url(theme_get_setting('logo.url')));
  $variables['logopath'] = \Drupal::service('file_url_generator')->generateString(theme_get_setting('logo.url'));


  // Add library with custom CSS.
  if (theme_get_setting('custom_css')) {
    $variables['#attached']['library'][] = 'bfd_systopia/custom-styling';
  }
};

/**
 * Set a placeholder for all search form elements.
 */
function  bfd_systopia_preprocess_input(&$variables) {
  if ($variables['attributes']['type'] == 'search') {
    $variables['attributes']['placeholder'] = t('Search');
  }
}

/**
 * Implements theme_preprocess_textarea.
 */
function  bfd_systopia_preprocess_textarea(&$variables) {
  $variables['attributes']['class'][] = 'form-control';
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for erro page 403 & 404.
 */
function  bfd_systopia_theme_suggestions_page_alter(array &$suggestions, array $variables) {

  $path_args = explode('/', trim(\Drupal::service('path.current')->getPath(), '/'));
  $suggestions = theme_get_suggestions($path_args, 'page');
  $http_error_suggestions = [
    'system.401' => 'page__401',
    'system.403' => 'page__403',
    'system.404' => 'page__404',
  ];

  $route_name = \Drupal::routeMatch()->getRouteName();
  if (isset($http_error_suggestions[$route_name])) {
    $suggestions[] = $http_error_suggestions[$route_name];
  }

  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $content_type = $node->bundle();
    $suggestions[] = 'page__' . $content_type;
  }
}

/**
 * Implements theme suggestion for form by ID.
 */
function  bfd_systopia_theme_suggestions_form_alter(array &$suggestions, array $variables) {
  // Add template suggestion based on form ID.
  $suggestions[] = 'form__' . $variables['element']['#form_id'];
  // Add template suggestion based on form ID and parent comment ID.
  if ($pid = \Drupal::routeMatch()->getParameter('pid')) {
    $suggestions[] = 'form__' . $variables['element']['#form_id'] . '__reply';
    $suggestions[] = 'form__' . $variables['element']['#form_id'] . '__reply__' . $pid;
  }
}

/**
 * Implements hook_form_system_theme_settings_alter().
 */
function  bfd_systopia_form_system_theme_settings_alter(&$form, FormStateInterface &$form_state, $form_id = NULL) {
  if (isset($form_id)) {
    return;
  }

  // Get bfd theme path.
  global $base_url;
  // deprecated d10 -  $bfd_path = drupal_get_path('theme', 'bfd_systopia');
  $bfd_path = \Drupal::service('extension.list.theme')->getPath('bootstrap_for_drupal');
  $custom_css_path = 'public://bfd-custom.css';
  $custom_css_dir = str_replace($base_url . '/', "", \Drupal::service('file_url_generator')->generateAbsoluteString($custom_css_path));
  // deprecated d10 - $custom_css_url = file_create_url($custom_css_path);
  $custom_css_url = \Drupal::service('file_url_generator')->generateAbsoluteString($custom_css_path);


  $form['bfd_custom'] = [
    '#type' => 'fieldset',
    '#title' => t('bfd Customization'),
    '#weight' => -10,
  ];

  $form['bfd_custom']['custom_css'] = [
    '#type' => 'checkbox',
    '#title' => t('Use "bfd-custom.css"'),
    '#description' => t('Include bfd-custom.css file to override or add custom css code without subthememing/hacking bfd Theme.'),
    '#default_value' => theme_get_setting('custom_css'),
  ];

  $form['bfd_custom']['bfd_custom_check'] = [
    '#type' => 'fieldset',
    '#title' => t('Custom CSS file check'),
    '#weight' => 50,
    '#states' => [
      // Hide the settings when the cancel notify checkbox is disabled.
      'visible' => [
        ':input[name="custom_css"]' => ['checked' => TRUE],
      ],
    ],
  ];

  if (file_exists($custom_css_path)) {
    $form['bfd_custom']['bfd_custom_check']['custom_css_description'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['messages', 'messages--status'],
      ],
      'message' => [
        '#markup' => t('Custom CSS file Found in: @css', ['@css' => $custom_css_dir]),
      ],
    ];
  }
  else {
    $form['bfd_custom']['bfd_custom_check']['custom_css_not_found'] = [
      '#type' => 'container',
      '#attributes' => [
        'class' => ['messages', 'messages--error'],
      ],
      'message' => [
        '#markup' => t('Custom CSS file not found. You must create the @css file manually.', ['@css' => $custom_css_dir]),
      ],
    ];
  }
}

/**
 * @file
 * Functions to support theming in the Classy theme.
 *
 * No changes that impact functionality should be made to this file, as Classy
 * will be deprecated in Drupal 9. Changes should instead be made in the core
 * themes Bartik, Seven, Claro and/or Umami.
 */

// use Drupal\Core\Form\FormStateInterface;
// use Drupal\views\Form\ViewsForm;

/**
 * Implements hook_preprocess_links__media_library_menu().
 *
 * This targets the menu of available media types in the media library's modal
 * dialog.
 *
 * @todo Do this in the relevant template once
 *   https://www.drupal.org/project/drupal/issues/3088856 is resolved.
 */
function bfd_systopia_preprocess_links__media_library_menu(array &$variables) {
  foreach ($variables['links'] as &$link) {
    $link['link']['#options']['attributes']['class'][] = 'media-library-menu__link';
  }
}

/**
 * Implements hook_form_alter().
 */
function bfd_systopia_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  $form_object = $form_state->getFormObject();
  if ($form_object instanceof ViewsForm && strpos($form_object->getBaseFormId(), 'views_form_media_library') === 0) {
    $form['#attributes']['class'][] = 'media-library-views-form';
  }
}

/**
 * Implements hook_preprocess_image_widget().
 */
function bfd_systopia_preprocess_image_widget(array &$variables) {
  // This ist moved form the stable hook implementation here - orginal see below
  if (!empty($variables['element']['fids']['#value'])) {
    $file = reset($variables['element']['#files']);
    // @phpstan-ignore-next-line
    $variables['data']['file_' . $file->id()]['filename']['#suffix'] = ' <span class="file-size">(' . bfd_systopia_format_size($file->getSize()) . ')</span> ';
  }

  // start classy
  $data = &$variables['data'];

  // This prevents image widget templates from rendering preview container HTML
  // to users that do not have permission to access these previews.
  // @todo revisit in https://drupal.org/node/953034
  // @todo revisit in https://drupal.org/node/3114318
  if (isset($data['preview']['#access']) && $data['preview']['#access'] === FALSE) {
    unset($data['preview']);
  }
}

/**
 * No changes that impact functionality should be made to this file, as Classy
 * will be deprecated in Drupal 9. Changes should instead be made in the core
 * themes Bartik, Seven, Claro and/or Umami.
 */


// stable

/**
 * @file
 * Functions to support theming in the Stable theme.
 */

// use Drupal\Component\Utility\Html;

/**
 * Implements hook_library_info_alter().
 */
function bfd_systopia_library_info_alter(&$libraries, $extension) {
  // Add removed css/filter.admin.css file back so that themes overriding
  // this file continue getting same behavior until Drupal 9.
  if ($extension === 'filter') {
    if (isset($libraries['drupal.filter.admin'])) {
      $libraries['drupal.filter.admin']['css']['theme']['css/filter.admin.css'] = [];
    }
    if (isset($libraries['drupal.filter'])) {
      $libraries['drupal.filter']['css']['theme']['css/filter.admin.css'] = [];
    }
  }
}

/**
 * Implements template_preprocess_links().
 */
function bfd_systopia_preprocess_links(&$variables) {
  if (!empty($variables['links'])) {
    foreach ($variables['links'] as $key => $value) {
      if (!is_numeric($key)) {
        $class = Html::getClass($key);
        $variables['links'][$key]['attributes']->addClass($class);
      }
    }
  }
}

/**
 * Implements hook_element_info_alter().
 */
function bfd_systopia_element_info_alter(array &$info) {
  if (array_key_exists('text_format', $info)) {
    $info['text_format']['#process'][] = 'bfd_systopia_process_text_format';
  }
}

/**
 * The #process callback, for adding classes to filter components.
 *
 * @param array $element
 *   Render array for the text_format element.
 *
 * @return array
 *   Text_format element with the filter classes added.
 */
function bfd_systopia_process_text_format(array $element) {
  $element['format']['#attributes']['class'][] = 'filter-wrapper';
  $element['format']['guidelines']['#attributes']['class'][] = 'filter-guidelines';
  $element['format']['format']['#attributes']['class'][] = 'filter-list';
  $element['format']['help']['#attributes']['class'][] = 'filter-help';

  return $element;
}

/**
 * Implements hook_preprocess_image_widget().
 */
// same hook as classy - moved to classy hook
// function stable_preprocess_image_widget(&$variables) {
//   if (!empty($variables['element']['fids']['#value'])) {
//     $file = reset($variables['element']['#files']);
//     // @phpstan-ignore-next-line
//     $variables['data']['file_' . $file->id()]['filename']['#suffix'] = ' <span class="file-size">(' . stable_format_size($file->getSize()) . ')</span> ';
//   }
// }

/**
 * Formats file size.
 */
function bfd_systopia_format_size($size) {
  $func = 'Drupal\Core\StringTranslation\ByteSizeMarkup::create';
  if (!is_callable($func)) {
    $func = 'format_size';
  }
  return $func($size);
}
